version: "3.2"
services:

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: onlyhome
      POSTGRES_PASSWORD: onlyhome
      POSTGRES_DB: Onlyhome
    ports:
      - "5432:5432"
   # volumes:
   #   - ./database:/var/lib/postgresql/data:rw

  backend:
    stdin_open: true
    container_name: backend 
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: postgres://onlyhome:onlyhome@database:5432/Onlyhome?schema=public
      APP_PORT: 80
    ports: ['80:80'] 
    depends_on:
      - database
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
      - uploads:/usr/app/uploads
    external_links:
            - mailhog

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:  
      - BACKEND_URL=http://localhost

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "5555:8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web interface port
    depends_on:
      - backend

#  nginx:
#    image: nginx:latest
#    ports:
#      - "8081:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - frontend
#      - backend

#  elasticsearch:
 #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
 #   container_name: elasticsearch
 #   environment:
 #     - discovery.type=single-node
 #   ports:
 #     - "9200:9200"
 #     - "9300:9300"
 #   ulimits:
 #     memlock:
 #       soft: -1
 #       hard: -1
 #   volumes:
 #     - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  uploads:

 # elasticsearch-data:
 #   driver: local